eval($q=%w[
d,l,b,a=[3,48,51,63];
z={?0=>[a,b,b,b,a,7],?1=>[d,d,d,d,d,7],?2=>[a,d,a,l,a,7],?3=>[a,d,a,d,a,7],?4=>[b,b,a,d,d,7],?5=>[a,l,a,d,a,7],?6=>[a,l,a,b,a,7],?7=>[a,d,d,d,d,7],?8=>[a,b,a,b,a,7],?9=>[a,b,a,d,a,7],?:=>[0,d,0,d,0,3]};
e=27.chr+91.chr;
$h=e+";43m";
$r=e+"0m";
s="eval($q=%w[#$q]+'')".chars.reverse;
p(s.length);
5.times{|i|Time.now.strftime('%H:%M:%S').chars.each{|c|z[c][5].downto(0){|x|print(((z[c][i]&1<<x).zero?&&'%s'||"#$h%s#$r")%s.pop)}};puts(s.pop+s.pop)};
]*'')